### ISSUE TITLE
Error access denied

### ISSUE THREAD

**Issue by ChristofLuytenGFI** [microsoftgraph/nodejs-sentiment-bot-sample#3]
I connect in the chat, a webpage opens with a code, I enter the code in the chat and then I get the error message "Error occured: Error: Access Denied

**Comment by jamescro** [comment]
Could you check your application registration and verify that this is the redirect uri assigned to the application? https://localhost:3980/botauth/aadv2/callback

**Comment by ChristofLuytenGFI** [comment]
Yes

I added a screenshot as attachment

Met vriendelijke groeten, Meilleures salutations, Kind regards,

Christof Luyten
Gfi
Analyst-Developer
Application Services Belgium
__

Technologielaan 11 – 0102 - B-3001 Heverlee - Belgium
Phone: +32 16 38 11 11

**Comment by jamescro** [comment]
Is it possible that you've hit your LUIS or Text Analytics quota?
Can you run Fiddler and send a trace of the call that is generating the error?

**Comment by ChristofLuytenGFI** [comment]
The messages between the bot and microsoft.online are tunneled and I am not able to catch them. It seems to go correctly untill the very end, when the bot has to use the token.

Maybe this can help:
I get an error in this piece of code:
`                    sentimentHelper_1.SentimentHelper.getSentimentScore(text).then((score) => {
                        session.endConversation('Sentiment Score: ${score}');
                    }, (err) => {
                        session.endConversation('Error occurred: ${err}');
                    });`

'results' contains a key but apparently not the correct one. The 'err' contains this message:

{ Error: Access Denied
    at IncomingMessage.<anonymous> (C:\Users\..\src\server\helpers\httpHelper.js:24:33)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  code: 401,
  message: 'Access Denied',
  innerError: '{ "statusCode": 401, "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription." }' }

I have tried it with different logins, nothing seem to work.

**Comment by jamescro** [comment]
Thanks for the additional information. That does narrow things down considerably. 
That error indicates either that there is a problem with how the request is structured (which I doubt is the problem here, since the sample is working for me) or that the subscription key is truly invalid for some reason.

Have you tried generating a new subscription key? Is it possible that you've hit the request quota for your subscription tier? Can you verify that you've [copied the subscription key correctly into the sample](https://github.com/microsoftgraph/nodejs-sentiment-bot-sample#get-a-key-for-the-text-analytics-api)?

Are you trying this with a language other than English? You can see a list of supported languages here, along with the associated codes: https://docs.microsoft.com/en-us/azure/cognitive-services/Text-Analytics/text-analytics-supported-languages

Note that if you're using a language other than English, you'll need to pass a different value/language code in the [body payload](https://github.com/microsoftgraph/nodejs-sentiment-bot-sample/blob/master/src/server/helpers/sentimentHelper.ts).

**Comment by ChristofLuytenGFI** [comment]
I made new subscription keys and checked the quota. It does not fix the problem. 
What do you mean with "Are you trying this with a language other than English?" I am trying everything in English. Is the language of my account an issue?
I tried the 'nodejs-connect-rest-sample' and that one works fine.

**Comment by jamescro** [comment]
Thanks for trying with the new subscription key. I asked about language because I notice that one of the things that this sample passes in its payload is a language key, and I'm trying to figure out if the service isn't liking something about the payload that you're sending.

Others who get that error when they hit cognitive services have found that the request they were sending to the service was broken in some way. The same request payload works for me, though, so I'm trying to determine whether there is something about your environment that is causing the sample request to fail. 

The sample passes body preview text from email messages that it finds in your inbox. Could you put a break in the code and determine what kinds of text are being passed through the request? Could there be a problem with the way the sample is serializing the text from your emails?

**Comment by ChristofLuytenGFI** [comment]
I found the bug. My text analysis cognitive service was located in East US instead of West US. After changing the line in sentimentHelper.js to
`httpHelper_1.HttpHelper.postJson(header, 'eastus2.api.cognitive.microsoft.com', '/text/analytics/v2.0/sentiment', payload).then((data) => {`
it worked fine.

Thanks for the help!
